[package]
name = "minimq"
version = "0.1.0"
authors = ["Max Rottenkolber <max@mr.gy>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.0"
enum-iterator = "0.6.0"
nb = "0.1.2"
heapless = "0.5.5"
generic-array = "0.14.3"
log = "0.4"
embedded-time = "0.9.1"

[dev-dependencies]
env_logger = "0.7"

[dependencies.embedded-nal]
git = "https://github.com/thejpster/embedded-nal"
