[package]
name = "minimq"
version = "0.1.0"
authors = ["Ryan Summers <ryan.summers@vertigo-designs.com>", "Max Rottenkolber <max@mr.gy>"]
edition = "2018"

description = "A minimal MQTT5 client designed for no_std platforms"
homepage = "https://github.com/quartiq/minimq"
repository = "https://github.com/quartiq/minimq"
documentation = "https://docs.rs//minimq"

readme = "README.md"
categories = ["embedded", "no-std", "database", "encoding"]
keywords = ["mqtt", "embedded", "client"]
license = "MIT"

[dependencies]
bit_field = "0.10.0"
enum-iterator = "0.6.0"
nb = "0.1.2"
heapless = "0.5.5"
generic-array = "0.14.3"
embedded-time = "0.9.1"
log = {version = "0.4", optional = true}

[features]
logging = ["log"]

[dev-dependencies]
env_logger = "0.7"

[dependencies.embedded-nal]
git = "https://github.com/thejpster/embedded-nal"
